const products = [
  {
    id: 1,
    categoryId: 2,
    title: 'Чехол для телефона Xiaomi Mi 11T Pro ',
    price: 590,
    image: '/img/box.jpg',
    colors: ['#361256', '#222'],
  },
  {
    id: 2,
    categoryId: 6,
    title: 'Толстовка с капюшоном',
    price: 2490,
    image: '/img/hoodie.jpg',
    colors: ['#8BE000', '#222'],
  },
  {
    id: 3,
    categoryId: 6,
    title: 'Портфель для ноутбука',
    price: 5490,
    image: '/img/case.jpg',
    colors: ['#222'],
  },
  {
    id: 4,
    categoryId: 6,
    title: 'Ремень тканевый',
    price: 1390,
    image: '/img/belt.jpg',
    colors: ['#222', '#b0b0b0'],
  },
  {
    id: 5,
    categoryId: 4,
    title: 'Радионяня Motorola MBP16',
    price: 3690,
    image: '/img/radio.jpg',
    colors: ['#73B6EA', '#b0b0b0'],
  },
  {
    id: 6,
    categoryId: 1,
    title: 'Ультразвуковая зубная щётка Playbrush Smart Sonic',
    price: 5660,
    image: '/img/toothbrush.jpg',
    colors: ['#222', '#b0b0b0'],
  },
  {
    id: 7,
    categoryId: 2,
    title: 'Смартфон Xiaomi Mi Mix 3 6/128GB',
    price: 21790,
    image: '/img/phone.jpg',
    colors: ['#222', '#fac6ec'],
  },
  {
    id: 8,
    categoryId: 3,
    title: 'Электроскейт Razor Cruiser',
    price: 24690,
    image: '/img/board.jpg',
    colors: ['#222'],
  },
  {
    id: 9,
    categoryId: 2,
    title: 'Смартфон Xiaomi Mi A3 4/64GB Android One',
    price: 14960,
    image: '/img/phone-2.jpg',
    colors: ['#222'],
  },
  {
    id: 10,
    categoryId: 2,
    title: 'Смартфон Xiaomi Redmi 6/128GB',
    price: 8960,
    image: '/img/phone-3.jpg',
    colors: ['#222', '#c7292a'],
  },
  {
    id: 11,
    categoryId: 3,
    title: 'Электрический дрифт-карт Razor Crazy Cart',
    price: 39900,
    image: '/img/bicycle.jpg',
    colors: ['#222', '#8BE000'],
  },
  {
    id: 12,
    categoryId: 3,
    title: 'Гироскутер Razor Hovertrax 2.0',
    price: 34900,
    image: '/img/wheels.jpg',
    colors: ['#222', '#b0b0b0'],
  },
  {
    id: 13,
    categoryId: 3,
    title: 'Детский трюковой самокат Razor Grom',
    price: 4990,
    image: '/img/scooter.jpg',
    colors: ['#222', '#c7292a'],
  },
  {
    id: 14,
    categoryId: 3,
    title: 'Роллерсёрф Razor RipStik Air Pro',
    price: 6690,
    image: '/img/ripstik.jpg',
    colors: ['#222', '#f3f863', '#73B6EA', '#fac6ec'],
  },
  {
    id: 15,
    categoryId: 5,
    title: 'Наушники AirPods с беспроводным зарядным футляром',
    price: 16560,
    image: '/img/airpods.jpg',
    colors: ['#222', '#b0b0b0'],
  },
  {
    id: 16,
    categoryId: 5,
    title: 'Наушники Sony',
    price: 30690,
    image: '/img/headphones.jpg',
    colors: ['#222', '#c7292a'],
  },
  {
    id: 17,
    categoryId: 7,
    title: 'Подушка ортопедическая',
    price: 3260,
    image: '/img/pillow.jpg',
    colors: ['#fac6ec'],
  },
  {
    id: 18,
    categoryId: 6,
    title: 'Маникюрный набор',
    price: 3890,
    image: '/img/manicure.jpg',
    colors: ['#222', '#b0b0b0'],
  },
];

export default products;
